apiVersion: apps/v1
kind: Deployment
metadata:
  name: bear
  labels:
    app: bear
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app: bear
        tier: frontend
    spec:
      containers:
      - name: bear
        image: "supergiantkir/animals:bear"
---
apiVersion: apps/v1
kind: Deployment  
metadata:
  name: moose
  labels:
    app: moose
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app: moose
        tier: frontend
    spec:
      containers:
      - name: moose
        image: "supergiantkir/animals:moose"
